services:
  apiproject:
    build: ./APIProject
    volumes:
      - ./APIProject:/apiproject
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
  
  mysite_react:
    build: ./mysite_react
    volumes:
      - ./mysite_react:/app
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - apiproject
